import { z } from "zod";
import { FormDataSchema } from "./schema";

type FormData = z.infer<typeof FormDataSchema>;

export const stepFields: { [key: string]: (keyof FormData)[] } = {
  1: [
    "appno",
    "date",
    "fname",
    "sname",
    "lname",
    "gender",
    "presadd",
    "permadd",
    "mothertongue",
    "nationality",
    "dob",
    "bloodgroup",
    "aadhaar",
    "pannumber",
    "mobile",
    "email",
    "img",
  ],
  2: [
    "parentname",
    "parentmobile",
    "parentemail",
    "relationshiptostudent",
    "occupation",
    "addressforcoresspondence",
    "challenge",
    "hearing",
    "ortho",
    "visual",
    "blind",
    "disable",

    "textbox11",
    "textbox12",
    "textbox13",
    "textbox14",
    "textbox15",

    "textbox21",
    "textbox22",
    "textbox23",
    "textbox24",
    "textbox25",

    "textbox31",
    "textbox32",
    "textbox33",
    "textbox34",
    "textbox35",

    "textbox41",
    "textbox42",
    "textbox43",
    "textbox44",
    "textbox45",
  ],
  3: ["program"],
  4: ["comments", "paymentMethods", "otherpaymentmode"],
  5: [
    "feestatus",
    "paidstatus",
    "amountpaid",
    "t11",
    "t12",
    "t13",
    "t21",
    "t22",
    "t23",
    "t31",
    "t32",
    "t33",
    "t41",
    "t42",
    "t43",
    "t51",
    "t52",
    "t53",
    "t61",
    "t62",
    "t63",
    "declarationplace",
    "declarationdate",
    "signApplicant",
    "signParent",
    "documents",
    "documentFiles",
    "feereceipt",
  ],
};
